name: 'VulnAPI Action'
description:
  'VulnAPI is an open-source project designed to help you scan your APIs for
  common security vulnerabilities and weaknesses.'
author: 'CerberAuth'
branding:
  icon: 'shield'
  color: 'gray-dark'

inputs:
  version:
    description: 'The version of the VulnAPI to use'
    required: true
    default: 'latest'

  curl:
    description: 'The curl command used to run API vulnerability scans'
    required: false

  openapi:
    description: 'The OpenAPI file used to run API vulnerability scans'
    required: false

runs:
  using: node20
  main: dist/index.js
