name: Check Transpiled JavaScript

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-dist:
    uses: cerberauth/ci/.github/workflows/action-check-dist.yml@main
