name: Lint Codebase

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  lint:
    uses: cerberauth/ci/.github/workflows/action-linter.yml@main
    secrets: inherit
