name: Lint Codebase

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  pull-requests: write
  statuses: write

jobs:
  lint:
    uses: cerberauth/ci/.github/workflows/action-linter.yml@main
    secrets: inherit
